export { default as Home } from "./home/Home";
export {default as AuthCheck} from "./authCheck/AuthCheck";
export { default as Login } from "./login/Login";
export { default as Register } from "./register/Register";
export { default as ForgotPassword } from "./forgotPassword/ForgotPassword";
export { default as PersonalOffice } from "./privateOffice/PersonalOffice";
export { default as Profile } from "./profil/Profile";
export { default as Settings } from "./profil/settings/Settings";
export { default as Withdraw } from "./profil/withdraw/Withdraw";
export { default as WithdrawFinally } from "./profil/withdraw/WithdrawFinally";
export {default as PaymentQrcode} from "./profil/paymentQrcode/PaymentQrcode";
export {default as PaymentCard} from "./profil/payment/PaymentCard";
export {default as ProfileBlank} from "./blank/ProfileBlank";